# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StochasticCtl < Formula
  desc "Stochastic — backtesting platform for trading strategies (CLI)"
  homepage "https://stochastic.sh"
  version "1.8.0"
  license "MIT"
  depends_on :macos

  url "https://github.com/stochastic-sh/stochastic/releases/download/v1.8.0/stochastic-ctl_1.8.0_darwin_universal.tar.gz"
  sha256 "a96ab54096191ac8db0d4105d47ca52cc80359b9fc9c01f422d29dcf8ff9ab14"

  define_method(:install) do
    bin.install "stochastic-ctl"
    bin.install "stochastic-engine"
    (share/"stochastic").install Dir["share/stochastic/*"]
  end

  def caveats
    <<~EOS
      This formula installs BOTH the CLI (stochastic-ctl) and the engine
      (stochastic-engine) that it runs.

      Stochastic needs a Docker engine for `infra up` (TimescaleDB + NATS).
      Install one of:
        - colima (lightweight, CLI):
            brew install colima docker docker-compose
            colima start
        - Docker Desktop (point-and-click):
            https://docs.docker.com/desktop/install/mac-install/

      Quick-start (after your Docker engine is running):

        stochastic-ctl infra up

        brew install --cask stochastic-sh/tap/stochastic

        open -a Stochastic
    EOS
  end
end
