# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StochasticCtl < Formula
  desc "Stochastic — backtesting platform for trading strategies (CLI)"
  homepage "https://stochastic.sh"
  version "0.19.1"
  license "MIT"
  depends_on :macos

  url "https://github.com/stochastic-sh/stochastic/releases/download/v0.19.1/stochastic-ctl_0.19.1_darwin_universal.tar.gz"
  sha256 "377c898f7fd19ad857470a84faf5b53a4b61b6e2bff0fbed4d467b023117800d"

  define_method(:install) do
    bin.install "stochastic-ctl"
    bin.install "stochastic-engine"
    (share/"stochastic").install Dir["share/stochastic/*"]
  end

  def caveats
    <<~EOS
      This formula installs BOTH the CLI (stochastic-ctl) and the engine
      (stochastic-engine) that it runs.

      Stochastic needs a Docker engine for `infra up` (TimescaleDB + NATS).
      Install one of:
        - colima (lightweight, CLI):
            brew install colima docker docker-compose
            colima start
        - Docker Desktop (point-and-click):
            https://docs.docker.com/desktop/install/mac-install/

      Quick-start (after your Docker engine is running):

        stochastic-ctl infra up

        brew install --cask stochastic-sh/tap/stochastic

        open -a Stochastic
    EOS
  end
end
