# This file was generated by GoReleaser. DO NOT EDIT.
cask "stochastic" do
  app "Stochastic.app"

  version "0.25.0"

  on_macos do
    sha256 "954f64e5830c5873d1aefc8c34eb0be6f89146edca8a5139a39ca996c22730d5"
    url "https://github.com/stochastic-sh/stochastic/releases/download/v#{version}/stochastic-dashboard_#{version}_darwin_universal.tar.gz"
  end

  name "stochastic"
  desc "Stochastic — backtesting platform for trading strategies (Dashboard)"
  homepage "https://stochastic.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stochastic"

  # No zap stanza required

  caveats <<~EOS
    Stochastic needs a Docker engine for its backtests (TimescaleDB + NATS).
    Install either colima (`brew install colima docker docker-compose`
    then `colima start`) or Docker Desktop
    (https://docs.docker.com/desktop/install/mac-install/).

    The dashboard launches the engine (stochastic-engine) and expects
    stochastic-ctl on PATH for some operations. Both ship in the CLI
    formula — install it via:

      brew install stochastic-sh/tap/stochastic-ctl

      stochastic-ctl infra up
  EOS
end
